### ISSUE TITLE
Breaks JS indenting

### ISSUE THREAD

**Issue by imiric** [mxw/vim-jsx#10]
Hey, sorry to be a pest, but I noticed that with this plugin installed, the indenting on all JS files (.js and .jsx) is broken.

Here's what I mean:
![](http://i.imgur.com/s2vE8WW.gif)

The cursor always returns to the beginning of the line, both in Normal mode and with `o` or in Insert mode and with `Enter`. This is with `set filetype=javascript` and `set nopaste`.

The JSX syntax highlighting works great, it's just that I really can't work with the indenting broken. Removing this plugin fixes the issue.

Thanks for your work!

**Comment by jarodtaylor** [comment]
I'm having this same issue and I have pangloss/vim-javascript loaded.

**Comment by mxw** [comment]
@jarodtaylor—Can you send me a paste or a gist of your ~/.vimrc?

**Comment by jarodtaylor** [comment]
I'm using a dotfiles config so I am using .local on my configs. 

```
set number
set t_ti= t_te=
set ts=2

set smarttab
set nolist
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2

set background=dark
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

let g:user_emmet_expandabbr_key = '<C-g>'
let g:use_zen_complete_tag = 1

let g:jsx_ext_required = 0
```

**Comment by mxw** [comment]
@jarodtaylor—If that's your entire config, you don't have this package included...

**Comment by musically-ut** [comment]
The reason for my woes along similar lines turned out to be a stray `javascript.vim` file in my local computer's `.vim/indent` folder. Removing that file did the trick for me. 

It is a little surprising that a file took precedence over the plugins I had installed (using `vim-plug`). I wonder if `vundle` and `pathogen` also yield precedence in similar ways or whether this is hard-coded within vim.

**Comment by Goblinlordx** [comment]
Had this same issue and removed the /indent/javascript file to resolve this.

**Comment by xream** [comment]
If you use vim-plug, this may help: `Plug 'mxw/vim-jsx', { 'do': 'rm ~/.vim/plugged/vim-jsx/after/indent/jsx.vim' }`

**Comment by musically-ut** [comment]
@xream But that will remove the indentation-aid for XML embedded in the Javascript.

**Comment by pzatrick** [comment]
I was having the same issue, then I commented out the entire contents of ~/.vim/plugged/vim-jsx/after/indent/jsx.vim, restarted vim then autoindent was working again in my javascript (but not in the embedded html, of course). I think that's good evidence that the problem is with that file.

**Comment by mxw** [comment]
...or it conflicts with some other file from some other package.

**Comment by webOS101** [comment]
I'm also having the same issue with the broken indent. Happy to help trace this down.  I don't seem to have a stray .vim/indent folder.

**Comment by webOS101** [comment]
As a followup, I disabled all add-ons except `vim-javascript` and `vim-jsx` and i still have the issue.  This is running on MacVim, if that's relevant.

**Comment by webOS101** [comment]
In debugging further I discovered I had somehow deleted the contents of my {{vim-javascript}} folder.  Once I restored the contents of the folder, it was all good again.  😭

**Comment by micheleb** [comment]
I also had a `javascript.vim` file (in my `~/.vim/syntax` folder) which prevented `vim-jsx` from working, but what fooled me was that I was using `js` as `FileType` in my `.vimrc` to set 2-space tabs for javascript files, when I should have used `javascript.jsx`. This is the correct line:

    au FileType javascript.jsx setlocal sw=2 sts=2 et

**Comment by mxw** [comment]
`javascript` should be fine there.  Are you sure there wasn't _another_ intervening file that was setting up a different autocmd?

**Comment by micheleb** [comment]
`javascript` works, too, thanks. But I wrote `js`, which didn't.

**Comment by wincent** [comment]
Was broken for me too, fixed by updating from d0ad98cf0e5a0 to eb656ed96435. (Didn't bother to bisect.)

**Comment by JofArnold** [comment]
I had this issue. Turns out it was conflicting with [sheerun/vim-polyglot](https://github.com/sheerun/vim-polyglot).

For anyone else having this issue, grep for `javascript.vim` and see where it appears. Then selectively remove those which aren't vim-jsx, vim-javascript

**Comment by StandardNerd** [comment]
I removed (respectively renamed) vim-jsx/after/indent/jsx.vim - file and got proper indentation in jsx again.

**Comment by ObserverZero** [comment]
I am having this problem as well. I'm currently using NeoVim, is that a problem? Here is my init.vim:
[init.txt](https://github.com/mxw/vim-jsx/files/1301169/init.txt)

**Comment by mxw** [comment]
@ObserverZero—Do you really need everything in that config in order to repro?  Could you try to trim down until you have a minimal repo `~/.vimrc`?

**Comment by ObserverZero** [comment]
Ok, I've taken out what must be irrelevant.

`
"-----------------------LOADING PACKAGES--------------------
source ~/.config/nvim/autoload/autoclose.vim
source ~/.config/nvim/autoload/plug.vim
source ~/.config/nvim/autoload/pathogen.vim
source ~/.config/nvim/autoload/common-functions.vim
source ~/.config/nvim/autoload/indent-object.vim
source ~/.config/nvim/autoload/type_helpers.vim
source ~/.config/nvim/autoload/kwbd.vim
source ~/.config/nvim/autoload/syntastic-conf.vim
source ~/.config/nvim/autoload/restore_view.vim
source ~/.config/nvim/bundle/vim-slime/plugin/slime.vim
"-----------------------------------------------------------


"----------SETS VIM LANGUAGE AND MINIMAL INTERFACE----------
lan en_US
set nosmd
set noru
set noshowmode
set laststatus=0 
set linebreak
set fo+=t
set cmdheight=1
set ignorecase
set autoindent
set smartindent
set incsearch
set fillchars=" "
set nocompatible
set hidden
set t_Co=256
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab|retab
set clipboard=unnamed
execute 'highlight FoldColumn ctermbg=0'
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
filetype plugin on
"-----------------------------------------------------------

" ------------------JS SYNTAX AND REACT NATIVE--------------
let g:jsx_ext_required = 0
set conceallevel=1
filetype plugin indent on
filetype off
"-----------------------------------------------------------


"------------------------PLUG MODULES-----------------------
call plug#begin('~/.config/nvim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'justinmk/vim-sneak'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'critiqjo/lldb.nvim'
Plug 'honza/vim-snippets'
Plug 'chrisbra/NrrwRgn'
Plug 'wellle/targets.vim'
Plug 'flazz/vim-colorschemes'
Plug 'kana/vim-textobj-user'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
call plug#end()
"-----------------------------------------------------------
`

**Comment by mxw** [comment]
So your issue only repros when you have _all_ those plugins enabled?  If not, please disable them until you figure out the minimal possible `~/.vimrc` which repros.

**Comment by mvattuone** [comment]
I've noticed that if I have `let g:jsx_ext_required = 0` enabled in my `~/.vimrc`, this issue happens. 

As soon as I comment it out, I am able to indent again.

**Comment by rogeriopvl** [comment]
I used a customized version of @xream 's suggestion:
```
Plug 'sheerun/vim-polyglot', { 'do': 'rm ~/.vim/plugged/vim-polyglot/after/indent/javascript.vim' }
```

This fixed the problem. The `vim-polyglot` indent file should be irrelevant enough for not having a noticeable impact.
