### ISSUE TITLE
Opening and closing colors don't match

### ISSUE THREAD

**Issue by kylelamse** [mxw/vim-jsx#100]
They need to be the same color for consistency.

**Comment by mxw** [comment]
JSX highlighting for XML elements matches vim's default XML highlighting.  This sounds like user error.

**Comment by kylelamse** [comment]
Would have been nice of you to put that very significant detail in the README or actually try to help me instead of writing my issue off as a "user error" and closing it. Kind of rude.

**Comment by mxw** [comment]
To be fair: Your issue has been reported in the past and comes up easily in a search of the GitHub issues for, e.g., "close tag".  You also didn't follow the instructions on the README for reporting issues...

A large majority of the issues reported for this (very minimalist and admittedly quite basic) plugin are not actually bugs or feature requests, so you might understand my brusqueness when you ping me without having done your due diligence.
