### ISSUE TITLE
How to enable the plugin for .es6 files?

### ISSUE THREAD

**Issue by markvincze** [mxw/vim-jsx#101]
I see that by setting `let g:jsx_ext_required = 0` I can enable vim-jsx for .js files.

Is there a way to enable the plugin for .es6 files as well?

**Comment by markvincze** [comment]
With quite a lot a googling I found one solution, adding this to .vimrc:

```
au BufRead,BufNewFile *.es6 setfiletype javascript
```

It's working, though I don't know if this is the canonical solution.

**Comment by mxw** [comment]
You probably want `javascript.jsx`.  This is the standard method of doing ftdetect; it's not specific to vim-jsx or any other language of package.

**Comment by markvincze** [comment]
@mxw 
Umm, what is `javascript.jsx`? Is it a vim plugin? I didn't find anything with Google.

**Comment by mxw** [comment]
It's the concatenation of two different filetypes—that's just how you separate them.

**Comment by markvincze** [comment]
Ah, so the command should be 
```
au BufRead,BufNewFile *.es6 setfiletype javascript.jsx
```
right? Thanks for the clarification!

**Comment by mxw** [comment]
Yes.
