### ISSUE TITLE
Syntax coloring doesn't handle functions as component children

### ISSUE THREAD

**Issue by petersendidit** [mxw/vim-jsx#106]
If you open up a file that has this JSX rather than colorizing the JSX it just all gets the same color.

```jsx
return (
  <ScrollSync>
    {({ onScroll, scrollLeft, scrollTop }) => {
      return (
         <Grid
           onScroll={onScroll}
           scrollLeft={scrollLeft}
           scrollTop={scrollTop}
           {...this.props}
         />
      );
    }}
  <ScrollSync>
);
```

![screen shot 2016-07-29 at 9 12 18 am](https://cloud.githubusercontent.com/assets/52149/17251022/92448edc-556c-11e6-99f4-5c984b6a74d8.png)

This is syntax used by [react-virtualized ScrollSync component](https://github.com/bvaughn/react-virtualized/blob/master/docs/ScrollSync.md)

**Comment by mxw** [comment]
Didn't read README.

**Comment by petersendidit** [comment]
Added missing ~/.vimrc snippet

**Comment by mxw** [comment]
I can't repro.  Is that the full contents of your ~/.vimrc?

**Comment by petersendidit** [comment]
Oops. Looks like its an issue with `othree/yajs.vim` and `mxw/vim-jsx`.  I had switch back to `pangloss/vim-javascript` to try to test and must not have reloaded my vimrc correctly or something. Sorry for the goose chase.
