### ISSUE TITLE
Error when I open a .js file

### ISSUE THREAD

**Issue by AnnatarHe** [mxw/vim-jsx#108]
My .vimrc like this:

``` vim
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'

let g:javascript_plugin_jsdoc=1
let g:jsx_pragma_required=1
```

When I open a `.js` file, the error always here:
![image](https://cloud.githubusercontent.com/assets/8704175/17356927/bf02640c-598c-11e6-9c01-abbf22273b73.png)

I press `Enter`, It can be run. How can I resolve this error ?

I use Gvim on Ubuntu 16.04

**Comment by mxw** [comment]
Is that the full contents of your ~/.vimrc?

**Comment by AnnatarHe** [comment]
.vimrc:
```vim
set hlsearch                  "高亮度反白
set backspace=2               "可随时用倒退键删除
set autoindent                "自动缩排
set ruler                     "可显示最后一行的状态
set showmode                  "左下角那一行的状态
set number                    "可以在每一行的最前面显示行号
set bg=dark                   "显示不同的底色色调
syntax on                     "进行语法检验，颜色显示
set wrap                      "自动折行
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab                  "将tab替换为相应数量空格
set smartindent
set guioptions-=e
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set nocompatible               " 设置 vim 为不兼容 vi 模式
"Toggle Menu and Toolbar
set guioptions-=m
set guioptions-=T
set linespace=15
set mouse-=a
set nowritebackup
set nobackup
set noswapfile
let mapleader=";"
vnoremap <Leader>y "+y
nmap <Leader>p "+p
nmap <Leader><space> :nohlsearch<cr>

"######下面可根据自己的需要，可以不选用#############
set encoding=utf8               "设置内部编码为utf8
set fileencoding=utf8            "当前编辑的文件编码
set guifont=Hack\ 12

filetype plugin on

let g:neocomplcache_enable_at_startup = 1
filetype off                   " 必须的

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" Plugin 'ryanoasis/vim-devicons'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'Raimondi/delimitMate'
Plugin 'lepture/vim-css'
Plugin 'wavded/vim-stylus'
Plugin 'fatih/vim-go'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'gosukiwi/vim-atom-dark'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'mattn/emmet-vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'ervandew/supertab'
"Plugin 'jdkanani/vim-material-theme'
call vundle#end()            " required
filetype plugin indent on

syntax enable

filetype plugin indent on     " 必须有

if has("gui_running")
    let g:isGUI = 1
    set guioptions=icpM
else
    let g:isGUI = 0
endif
" set cursorline cursorcolumn

" --------------Tagbar------------------------
let g:tagbar_width=35
let g:tagbar_autofocus=1

" --------------vim-javascript---------------
let g:javascript_plugin_jsdoc=1
let g:jsx_pragma_required=0


"-------------airline settings---------------
set laststatus=2
let g:airline_powerline_fonts=1
" let g:Powerline_symbols="fancy"
" let g:airline_symbols = {}
" let g:airline#extensions#tabline#enabled=1

"-------------ctrlp-settings---------------------
let g:ctrlp_custom_ignore = 'node_modules'
let g:ctrlp_open_new_file = 't'
map <Leader>f :CtrlPMRUFiles<CR>
map <Leader>t :NERDTreeToggle<CR>

"--------------snippets--------------------------
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

"-------------nerd-commenter--------------------
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1

"------------- multiple-cursors-----------------
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_start_key='<C-m>'
let g:multi_cursor_next_key='<C-m>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

"-------------emmet-settings--------------------
let g:user_emmet_mode='n'
let g:user_emmet_install_global = 0
autocmd FileType html,css,javascript EmmetInstall
" let g:user_emmet_leader_key='<C-Q>'

setlocal spell spelllang=en_us

set list
set listchars=tab:›\ ,trail:•,extends:>,precedes:<,nbsp:.
```

.gvimrc:
```vim
colorscheme atom-dark
```

please ignore Chinese comments :)

**Comment by mxw** [comment]
Please try bisecting your `~/.vimrc` to see if you can isolate the problem.

**Comment by AnnatarHe** [comment]
It solved.... I don't know why :joy: 

when I reset 
```vim
let g:jsx_pragma_required=1 // I set `0` those days
````

There is no error :joy:

**Comment by AnnatarHe** [comment]
Sorry, @mxw It doesn't work.

I just try to edit .jsx file and error is in .js file

I comment all plugins try to find what makes the error there.

But it disappears only when I comment the `mxw/vim-jsx` plugin.

I notice `ftdetect/javascript.vim` has the variable

![image](https://cloud.githubusercontent.com/assets/8704175/17657795/d7c61892-62f8-11e6-856f-ab78bc40a222.png)

**Comment by mxw** [comment]
What is the minimal `~/.vimrc` that this fails with for you?  Also, what version of vim are you using?

**Comment by AnnatarHe** [comment]
I am sure `let g:jsx_pragma_required=1` makes vim error

I just load vundle, vim-javascript, vim-jsx. nothing else.

I use Huge version with GTK2 GUI on Ubuntu 16.04 LTS
![image](https://cloud.githubusercontent.com/assets/8704175/17690212/a3180246-63bf-11e6-8458-cf16dd476c7d.png)

**Comment by maotora** [comment]
I too was facing this issue, and when i did as you said 

```javascript 
let g:jsx_pragma_required=1
```

It worked.

Is it suppose to be like this? Or is this another ```false fix``` and it'll probably **blow up** in the future?

**Comment by kafeltz** [comment]
I have this issue too. It's annoying because its complaining this error on JS files instead JSX.
I'm not a VIM scripter expert, but these variables are being defined inside a _if statement_ is this common for _vim plugins_?

**Comment by kafeltz** [comment]
I did this fix, https://github.com/mxw/vim-jsx/pull/121
I'm not expert but for some reason the variable must be declared inside the function scope, one scope above it's considered _not visible_. I need to understand better the _:b_ scope.

**Comment by cbrwizard** [comment]
I am having the same issue too.

**Comment by kafeltz** [comment]
This repo is dead.

**Comment by cbrwizard** [comment]
@kafeltz which one should I switch to? =]

**Comment by mxw** [comment]
Sorry folks—I just realized that I haven't been getting any notifications from issues and PRs for this repo in some time (though I did see these comments).

I will look into merging @kafeltz's fix next week, when I return from vacation.  Please feel free to make noise aggressively around next Saturday (~10 days from now) if you haven't heard from me by then.

**Comment by emostar** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by mxw** [comment]
looking now

**Comment by mxw** [comment]
Fixed.  Sorry folks—there's not a lot of testing for pragma-required, since it was deprecated a little while ago.

I'm still not getting notifications for this repo, unfortunately, and no amount of poking at options has fixed that...

**Comment by mxw** [comment]
Okay, I successfully figured out what was going wrong with my notifications...

This should make me more responsive, as new issues and PRs will remind me about any lingering ones...
