### ISSUE TITLE
Highlighting breaks with arrow functions in attribute values

### ISSUE THREAD

**Issue by jedireza** [mxw/vim-jsx#110]
Thanks for making `vim-jsx`.

Maybe this is similar to #70 but I wasn't able to see the screen shots. Arrow functions work fine outside of JSX but when used as values of attributes syntax highlighting breaks.

![screenshot from 2016-08-08 12-17-03](https://cloud.githubusercontent.com/assets/979929/17492871/acbd9080-5d62-11e6-9101-b1440d894750.png)

**Comment by mxw** [comment]
Could you:
(a) read the README; and 
(b) either close out the task, or post the raw text of your repro case in a comment or in a Gist?

**Comment by jedireza** [comment]
😳 Sorry, I totally missed the troubleshooting section. My apologies.

 - I've read the README.
 - I'm using `jelera/vim-javascript-syntax` (`9e019fc`)
 - I uninstalled `jelera/vim-javascript-syntax` and installed `pangloss/vim-javascript` and it's working now.

Thank you.
