### ISSUE TITLE
Wrong indentation for multiple tags on the same line

### ISSUE THREAD

**Issue by Metamist** [mxw/vim-jsx#111]
I am only using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) and as far as I know I don't have any plugins that causes this.
Check out the screenshot below:

Result:
![](http://i.imgur.com/T9S4oLX.jpg)
Expected:
![](http://i.imgur.com/0Iqq38G.jpg)

When you have two tags on the same line, with a child inside them, the indent is applied as if they were on separate lines. In this case, there is 2 indents while there should only be one.
If I have 3 tags in a row, it will result in 3 indents rather than the expected 1.

For reference, this is the result in sublime:
![](http://i.imgur.com/wdneKAY.jpg)

If it helps, I am on Windows 8.1, using [neovim-qt](equalsraf/neovim-qt).

**Comment by mxw** [comment]
I get the same indentation in any `*.xml` or `*.html` file—do you not?  `vim-jsx` should be delegating to the standard XML indentation for JSX regions, and it seems to be doing that as expected.

**Comment by Metamist** [comment]
Yes, you're right, should have thought about that!
