### ISSUE TITLE
Indent problem with react ternary

### ISSUE THREAD

**Issue by mnbroatch** [mxw/vim-jsx#112]
Hi, I'm using pangloss vim and there's a pretty minor issue I'm seeing...

When using a ternary operator in react with jsx as the expressions, I get a wrong indentation.

It's a pretty ugly pattern anyway, and I'm refactoring it right immediately, but I thought you might want to know, for completeness' sake.

![screen shot 2016-08-15 at 10 02 38 pm 2 copy](https://cloud.githubusercontent.com/assets/18113135/17688499/97c68812-6334-11e6-9620-245953bac674.png)

**Comment by mxw** [comment]
I'm... not really sure what indentation you're expecting here.  There are more parallel stylistic choices that can lead to reasonable indentation with a nested ternary-selected element—I've attached an example—but you can't expect an indenter to support all possible desired styles...

![screen shot 2016-08-16 at 2 46 25 am](https://cloud.githubusercontent.com/assets/1013739/17690322/bced147c-635b-11e6-9455-59d05dcf5d37.png)
