### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by sassanh** [mxw/vim-jsx#117]
Can we take care of things like this:
```
const node = <div
    x="y"
    onClick={() =>
            this.xyz()
    }>
    </div>;
```
`this.xyz()` has one extra indent. It doesn't happen in normal js:
```
const a = () =>
    this.xyz();
```
Not very important but I just thought maybe you can fix it easily. I have few other more cases and I can share those here if you're interested.

**Comment by mxw** [comment]
Your formatting for the `<div>` disobeys the JSX style guidelines (at least as they were originally...), so `vim-jsx` does not support it.  I've attached an image of the "correct" styling, which `vim-jsx` indents exactly as shown.

<img width="157" alt="screen shot 2016-09-11 at 2 24 50 pm" src="https://cloud.githubusercontent.com/assets/1013739/18419573/e58436ce-782b-11e6-9820-835c59c3af9a.png">

**Comment by sassanh** [comment]
I see, thanks for info.
