### ISSUE TITLE
Incorrect highlight in arrow-functions without body

### ISSUE THREAD

**Issue by alexey-broadcast** [mxw/vim-jsx#118]
There is an arrow-function without body. Highlight is broken when we don't conclude jsx to parens:

With parens (correct highlight):
![image](https://cloud.githubusercontent.com/assets/3949614/18543808/52e10e34-7b3a-11e6-8d05-fd09beca9ee2.png)

Without parens (incorrect highlight):
![image](https://cloud.githubusercontent.com/assets/3949614/18543795/47d009c8-7b3a-11e6-9636-b18c48cc72b5.png)

**Comment by mxw** [comment]
I can't repro, and you didn't read the README.

**Comment by alexey-broadcast** [comment]
Example vimrc:
[vimrc.txt](https://github.com/mxw/vim-jsx/files/474591/vimrc.txt)

Example source file:
[testfile.jsx.txt](https://github.com/mxw/vim-jsx/files/474592/testfile.jsx.txt)

Got this:
![image](https://cloud.githubusercontent.com/assets/3949614/18549631/6191a3ee-7b58-11e6-9257-75b7edff8f0a.png)
