### ISSUE TITLE
jsx and template literals

### ISSUE THREAD

**Issue by weslleyaraujo** [mxw/vim-jsx#119]
hey great work btw! :)

I noticed that mixing jsx w/ template literals bugs out the syntax:

![screen shot 2016-09-30 at 2 30 46 pm](https://cloud.githubusercontent.com/assets/2286385/19007644/d5b8e9f8-871a-11e6-9cac-1135ab4fc519.png)

I am using the following plugins/syntax schemas:

```bash
" Filetype off is required by vundle
filetype off
set rtp+=$HOME/.vim/bundle/vundle/
call vundle#begin("$HOME/.vim/bundle")

" let Vundle manage Vundle (required)
Bundle 'gmarik/vundle'

" Generic
Plugin 'mattn/emmet-vim'
Plugin 'editorconfig/editorconfig-vim'

" js
Plugin 'gavocanov/vim-js-indent', { 'for': ['javascript', 'javascript.jsx'] }
Plugin 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
Plugin 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] }

" Syntax hightlighting & colors
Plugin 'joshdick/onedark.vim'

call vundle#end()

" Filetype plugin indent on is required by vundle
filetype plugin indent on
```

**Comment by meriadec** [comment]
If your file has the `.js` extension and not `.jsx`, you need to add
```
let g:jsx_ext_required = 0
```
to your vimrc.
I didn't reproduced your problem:

![screen shot 2016-10-13 at 17 21 02](https://cloud.githubusercontent.com/assets/315259/19355200/d3aecb74-9169-11e6-86a0-c6ef779d2629.png)

**Comment by weslleyaraujo** [comment]
that's awesome, working properly now!

I must have missed that from the docs

thanks :)

**Comment by franekxtb** [comment]
Hey, I have exacly the same problem as @meriadec. Added `let g:jsx_ext_required = 0` but it didn't help
