### ISSUE TITLE
vim-emmet + vim-jsx hangs vim (neovim)

### ISSUE THREAD

**Issue by vyorkin** [mxw/vim-jsx#122]
when I visual-select a word and type a hotkey to wrap it with a tag (.e.g. `div`) it causes vim to hang.

here is my neovim version output: https://gist.github.com/vyorkin/a7b85ea02ad830a88cf2dda7fbc1028f

**Comment by kyrisu** [comment]
I will also add that it breaks several other emmet commands ex. `emmet#splitJoinTag()` (`<C-y>j`) or `emmet#moveNextPrev(0)` (`<C-y>n`). 

I'm using nvim in Arch Linux under urxvt - so I can stop the command by issuing `<C-c>`.

Disabling vim-jsx fixes the issue (emmet works as expected)

**Comment by mxw** [comment]
I don't know what vim-emmet is, but vim-jsx does not depend on it, so getting them to play nice together isn't this wheelhouse, I think.

**Comment by kyrisu** [comment]
Just so you know it is actually working now. Somewhere along the way, some update fixed it :)

Also @mxw emmet a really nice way of quickly writing HTML (or jsx :) ) definitely worth checking out.

**Comment by vyorkin** [comment]
thanks @kyrisu !

**Comment by mxw** [comment]
Cool, good to know.  Sorry it took so long to respond—I only recently figured out why I wasn't getting any notifications for this repo...
