### ISSUE TITLE
Syntax broken

### ISSUE THREAD

**Issue by francescarpi** [mxw/vim-jsx#123]
Hi everyone,

When I use a function directly in jsx, the syntax it broken. I prefer use this syntax for prevent performance mistakes. (https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.a304t8dlm)

![vimjsx](https://cloud.githubusercontent.com/assets/287872/20179088/b018cb64-a754-11e6-9cb3-1c73cb722c15.gif)

¿Do you know how can I fix it?

Thanks.

**Comment by MaxMEllon** [comment]
This pugin is very nice, but, I also hit the problem.
So I developed a new syntax plugin.
Please use [vim-jsx-pretty](https://github.com/MaxMEllon/vim-jsx-pretty) if you want.


![2016-11-18 1 15 30](https://cloud.githubusercontent.com/assets/9594376/20397288/8a17b03c-ad2c-11e6-80e6-7594c013747e.png)

![2016-11-18 1 20 00](https://cloud.githubusercontent.com/assets/9594376/20397460/29648192-ad2d-11e6-8beb-ca568296726a.png)

I am doing a respect vim-jsx.

**Comment by francescarpi** [comment]
Yeah!

Thanks guy. Your plugin work really fine!

**Comment by valerybugakov** [comment]
@MaxMEllon what theme do you have on the screenshot? I want it too 😃

**Comment by MaxMEllon** [comment]
@valerybugakov 

theme of diagram1 is default and next settings.
https://github.com/MaxMEllon/.vim/blob/master/ftplugin/javascript.vim#L7-L12

diagram2 is [tomasr](https://github.com/tomasr/molokai).
(forked to modify)

**Comment by mxw** [comment]
I believe this was fixed some time ago via a separate issue.  Closing out.
