### ISSUE TITLE
Syntax highlight breaks with template strings

### ISSUE THREAD

**Issue by arnarthor** [mxw/vim-jsx#125]
Hey, I'm not sure what it is that is triggering my syntax highlight to break.
![image](https://cloud.githubusercontent.com/assets/4514159/21746952/ae492360-d54e-11e6-885e-2bbb0cca6efc.png)
In the attached screenshot it randomly breaks in the JSX syntax in a helper function and the rest of the class declaration gets completely broken due too this. 

Other javascript plugins I'm using are `pangloss/vim-javascript`.

This works in some components but in others, where I have template strings it seems to break.

There at least seems to be a pattern of this breaking immediately after using a template string for me.

**Comment by arnarthor** [comment]
Another similar example 
![image](https://cloud.githubusercontent.com/assets/4514159/21746976/651f1d60-d54f-11e6-800d-ada65844c275.png)

**Comment by arnarthor** [comment]
This somehow solved itself when installing syntastic. Which I find odd, but I'll take it

**Comment by trevorwhitney** [comment]
Sorry to open an old issue, please let me know if it's already be addressed elsewhere. I'm still having this problem despite also having syntastic installed, any ideas?

**Comment by BrennanRoberts** [comment]
@trevorwhitney just had this problem and #119 had the fix.

**Comment by trevorwhitney** [comment]
awesome, thanks!

**Comment by antialias** [comment]
@BrennanRoberts and @trevorwhitney #119 ends with a reminder to use `.jsx` as the file extension or enable this plugin to work with `.js` files, but it does not address the current issue. I'm able to reproduce it myself in a `.jsx` file.

**Comment by antialias** [comment]
@arnarthor I believe that this issue is still valid; I'm able to reproduce it in a `.jsx` file.

**Comment by mxw** [comment]
Happy to look into this if someone can provide a minimal repro case in a format which allows me to test without typing every character seen in an image.

**Comment by mrozbarry** [comment]
```
const test = "foo"
const jsx = (
  <div>
    <div attr={`bar ${test} baz`} />
  </div>
)
```

Which highlights `bar` all the way to the end. I'm guessing it's detecting the closing brace of `${test}` and not knowing how to close the string.

**Comment by mxw** [comment]
Here's what I see, which seems correct to me:

<img width="299" alt="screen shot 2017-11-06 at 1 25 06 pm" src="https://user-images.githubusercontent.com/1013739/32457139-f716a5fa-c2f5-11e7-89c5-65fc5ba828b2.png">

**Comment by mrozbarry** [comment]
Well, I feel dumb.  I guess I had commented out this plugin a few months ago while testing something and didn't re-enabled it. Everything is working fine now.

So, @mxw, awesome work, things are 💯

**Comment by szchenghuang** [comment]
@mxw, I still see the issue in a corner case, either in a `.js` or a `.jsx` extension.

<img width="414" alt="syntax-broken" src="https://user-images.githubusercontent.com/6309412/54336631-8c3e9c00-4667-11e9-824a-c43c9bca977f.png">

while this one is fine
<img width="626" alt="syntax-ok" src="https://user-images.githubusercontent.com/6309412/54336638-906ab980-4667-11e9-9cf6-1cf09b78e77b.png">
