### ISSUE TITLE
Support for <style jsx>?

### ISSUE THREAD

**Issue by danawoodman** [mxw/vim-jsx#134]
How could support for embedded [styled JSX](https://github.com/zeit/styled-jsx) style tags work? Eg:

```js
    <style jsx>{`
      h1, a {
        font-family: "Arial";
      }

      ul {
        padding: 0;
      }

      li {
        list-style: none;
        margin: 5px 0;
      }

      a {
        text-decoration: none;
        color: blue;
      }

      a:hover {
        opacity: 0.6;
      }
    `}</style>
```

**Comment by mxw** [comment]
You can probably do a similar trick with importing the CSS syntax package, and jumping into it when you see the `<style jsx>` tag (with higher precedence than regular JSX tags, of course).  Feel free to try putting up a PR.

**Comment by mike3run** [comment]
@danawoodman there is https://github.com/alampros/vim-styled-jsx

i think this can be closed?
