### ISSUE TITLE
Should handle backticks in JSX

### ISSUE THREAD

**Issue by alanhamlett** [mxw/vim-jsx#138]
```
<input type="`${type}`" />
```

The above JSX breaks syntax highlighting.

**Comment by alanhamlett** [comment]
Nevermind, adding this to my vimrc fixed it:

`let g:jsx_ext_required = 0 " Allow JSX in normal JS files`

**Comment by mads-cbx** [comment]
How'd you get it to work? I have the same issue

**Comment by TrySound** [comment]
@mads-cbx 
```js
<input type={`${type}`} />
```

**Comment by mads-cbx** [comment]
Already did :cry:
