### ISSUE TITLE
Unexpected syntax breakage with React stateless component

### ISSUE THREAD

**Issue by danawoodman** [mxw/vim-jsx#140]
JSX tags are breaking my syntax highlighting, as show in this video:
![](https://cl.ly/l3GD/Screen%20Recording%202017-06-17%20at%2010.58%20AM.gif)

If I set the format to `javascript` highlight for everything but JSX works (expected) but If I change to `javascript.vim` everything works up to the JSX tags. If I inspect the syntax that is being used after the JSX tags I get `jsxRegion` which shouldn't be.

- Using neovim (latest)
- Using `pangloss/vim-javascript` and `mxw/vim-jsx`
- Installed latest version of both libraries
- Using vim-plug

Any thoughts about what might be wrong?

**Comment by danawoodman** [comment]
Wow, ok figured it out but it was very much not intuitive. I had the following set in my `.vimrc`:

```vim
let xml_syntax_folding=1
```

Commenting that out fixes syntax highlighting for me. Perhaps this should be in the readme?

**Comment by mxw** [comment]
Interesting that you should mention adding that to the README—I did so about a year ago.  Unfortunately, it doesn't help if you don't read it...
