### ISSUE TITLE
Allow for override of attribute indentation

### ISSUE THREAD

**Issue by saponifi3d** [mxw/vim-jsx#145]
It'd be nice if you could set the attribute indentation separately from the main attribute indentation.

I've found having the attribute be spaced 2 instead of 4 helps readability of what's an attribute, however this plugin enforces them to be equal.

For example:
```jsx
<Component
    attr1="/default-path"
    attr2="legoland"
    attr3={action('onClick')}
>
    <AnotherComponent />
</Component>
```

vs

```jsx
<Component
  attr1="/default-path"
  attr2="legoland"
  attr3={action('onClick')}
>
    <AnotherComponent />
</Component>
```

**Comment by mxw** [comment]
This is a wontfix because this logic is dictated by the XML indentation shipped with vim.
