### ISSUE TITLE
ES6 Template Causes formatting issue when used inside HTML prop

### ISSUE THREAD

**Issue by 902Labs** [mxw/vim-jsx#150]
This breaks formatting.

```
function emailLink(email) {
	return <a href={`mailto:${email}`} className="underline">{email}</a>;
}
```

![screenshot 2017-11-17 14 23 51](https://user-images.githubusercontent.com/4053376/32964969-f5cb25da-cba2-11e7-837e-3174ddd7c078.png)

**Comment by MacgyverMartins** [comment]
I had the same error today, but for some reason it fixed when I deleted and pasted all the code again

**Comment by MacgyverMartins** [comment]
I try your code on my Vim and it works fine

**Comment by mxw** [comment]
Read README.

**Comment by thallada** [comment]
@902Labs would you happen to have [vim-jsx-typescript](https://github.com/peitalin/vim-jsx-typescript) installed too? I had the same issue and narrowed it down to that plugin.
