### ISSUE TITLE
syntax/xml.vim not present

### ISSUE THREAD

**Issue by teejK** [mxw/vim-jsx#156]
```
Error detected while processing /Users/tony.jiang/.vim/plugged/vim-polyglot/after/syntax/jsx.vim:
line   19:
E484: Can't open file syntax/xml.vim

```
Manually copying xml.vim from https://github.com/othree/xml.vim has solved this issue, but this is a bit hacky no? 

Using vim-polyglot

**Comment by mxw** [comment]
xml.vim is included with your vim installation; it's a vim system file.  This sounds like it may be an issue with vim-polyglot, which vim-jsx does not maintain support for.
