### ISSUE TITLE
Incorrect highlight in *.js files

### ISSUE THREAD

**Issue by Xyzor** [mxw/vim-jsx#163]
Hello!

I made sure and set myself the `g:jsx_ext_required=0` too.

Still it's only works if I manualy set the filetype to `javascript.jsx`.

I'm using the [vim-polyglot](https://github.com/sheerun/vim-polyglot) plugin, and nothing more syntax like plugin.

Is there somethin else that I have to set to make it work with *.js files?

**Comment by mxw** [comment]
vim-polyglot contains maybe hundreds of packages inside of it.  I can't help unless you can provide me with a minimal ~/.vimrc and package set that repros your issue, which means you'd probably have to stop using vim-polyglot.
