### ISSUE TITLE
jsx indenting breaks when changing colorscheme

### ISSUE THREAD

**Issue by kbrah** [mxw/vim-jsx#166]
So I came across this weird behavior that when I change my colorscheme the jsx indentation breaks. No idea why this happens and if changing the colorscheme is the only way to break it. Colorschemes that I used were onedark and jellybeans.

before:
```
return [
      <div>
        <div>
          {hi}
        </div>
      </div>,
      <div>
        {hi}
      </div>
    ]
```
after:
```
return [
      <div>
        <div>
          {hi}
      </div>
    </div>,
      <div>
        {hi}
      </div>
      ]
```

**Comment by mxw** [comment]
I can't repro this.  Additionally, a colorscheme should never affect your indentation, so it's likely you accidentally changed something else as well.
