### ISSUE TITLE
Support ES6 template literals

### ISSUE THREAD

**Issue by alxdnlnko** [mxw/vim-jsx#167]
It seems to be not so difficult to support [ES6 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

It is already used in new Polymer projects and [lit-html](https://github.com/Polymer/lit-html).

```
render() {
  return html`
    <h1>Hello</h1>
  `
}
```

Tried to redefine the jsTemplateString region (added jsxRegion to it), and it works, but I don't know the right way of doing this :)

```
syntax region  jsTemplateString   start=+`+  skip=+\\`+  end=+`+     contains=jsTemplateExpression,jsSpecial,jsxRegion,@Spell extend
```

**Comment by mxw** [comment]
This is probably most suitable for the base JS/ES plugin rather than vim-jsx.  Maybe submit a PR to vim-javascript?
