### ISSUE TITLE
Recent update breaks YouCompleteMe file path completion

### ISSUE THREAD

**Issue by dj-foxxy** [mxw/vim-jsx#174]
Recently, file path completion provided by YouCompleteMe fails to work when vim-jsx is loaded, fine otherwise.

**Comment by kkoomen** [comment]
I do have the exact same problem recently. I went back into the commit history and when I go to the following commit:

```
c6d0fd7 <mxw@users.noreply.github.com> Merge pull request #61 from simonratner/feature/yajs-no-reserved (2 years, 10 months ago)
```

This is the one that breaks stuff for me. What I do not understand here is that my completion broke since a week ago, but this has been merged 2 years ago.

**Comment by iEricKoh** [comment]
Same problem, any update?

**Comment by dj-foxxy** [comment]
This issue appears to have gone away.
