### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by dabvid** [mxw/vim-jsx#18]
I have Installed 'pangloss/vim-javascript' and in the top of my jsx file I have /** @jsx React.DOM */
I am using Vundle. Did try commenting out all Bundles except vim-jsx and vim-javascript. 
Still can't get it to work.

Could it perhaps be something else in my <a href="https://gist.github.com/dabvid/66730a0f2356b190f7e8">.vimrc</a> that's causing the issue?

**Comment by olalonde** [comment]
This seems to work:

```javascript
var React = require('react'),
  Router = require('react-router');

module.exports = React.createClass({
  mixins: [Router.State],

  render: function() {
    var isActive = this.isActive(this.props.to, this.props.params, this.props.query);
    var className = isActive ? 'active' : '';
    var link = Router.Link(this.props);
    var link = (
      <Router.Link {...this.props} />
    );
    return <li className={className}>{link}</li>;
  }
});
```

I named this component LiLink.

**Comment by franleplant** [comment]
Works for me! Im using Vundle

**Comment by adam-beck** [comment]
I couldn't get this to work either with Vundle. Not a vim nor Vundle expert so I cannot provide more details.

**Comment by adam-beck** [comment]
@dabvid not to sound like I'm patronizing but how are you sure it is not highlighting correctly?
