### ISSUE TITLE
Break Tags Not Right

### ISSUE THREAD

**Issue by redreceipt** [mxw/vim-jsx#180]
It's not quite getting my syntax correct, specifically with `<br>` tags. Trying to figure out what may be going wrong under the covers. Screenshot attached.

![screen shot 2018-10-04 at 2 46 28 pm](https://user-images.githubusercontent.com/2659478/46495861-86a17800-c7e4-11e8-974e-e45990d79c9b.png)

**Comment by marcelothomaz** [comment]
Same problem here, was working before, not sure what changed. I installed a couple of more packages and can't figure out what is breaking it. I tried removing everything and leaving only vim-jsx and vim-javascript with no success

**Comment by nstylo** [comment]
I know this issure is almost a year old, but this issue does not seem to be fixed:

![image](https://user-images.githubusercontent.com/45883614/62127818-48c19300-b2d3-11e9-92cf-15841182f03f.png)

Any progress with this? Or any help needed?

**Comment by eusebiusmarcel** [comment]
Moving to https://github.com/MaxMEllon/vim-jsx-pretty
