### ISSUE TITLE
Syntax (or filetype) not working properly

### ISSUE THREAD

**Issue by elquimista** [mxw/vim-jsx#181]
What is the correct syntax/filetype for this plugin to work - `javascript` or `jsx`?

`Button.js` (`:set filetype=javascript`)
<img width="399" alt="screen shot 2018-10-23 at 8 47 11 pm" src="https://user-images.githubusercontent.com/14348482/47405115-d8169600-d704-11e8-81fa-97420c8062de.png">
☝️Syntax highlighting is correct for regular JS code, but insufficient highlighting for JSX part.

`Button.js` (`:set filetype=jsx`)
<img width="371" alt="screen shot 2018-10-23 at 8 47 50 pm" src="https://user-images.githubusercontent.com/14348482/47405131-ec5a9300-d704-11e8-9164-65d90e32aecd.png">
☝️Syntax highlighting seems to be correct for JSX code, but no highlighting for regular JS code.

I'm using Vim 8.1 with following line at the top of my `~/.vim/vimrc` file to load the plugin:
```vim
set runtimepath^=~/.vim/plugins/vim-jsx
````

**Comment by evmorov** [comment]
```
:set syntax=javascript.jsx
```

**Comment by elquimista** [comment]
Woah, it's simple as that.. wonder why I didn't see it in the README (or any other documentation). I'm closing this...
