### ISSUE TITLE
Curly braces dont match

### ISSUE THREAD

**Issue by franleplant** [mxw/vim-jsx#25]
Hi!
     Im seeing that curly braces inside a Jsx element dont match correctly in terms of color:

```javascript
<textarea
        className="message-composer"
        name="message"
        value={this.state.text}
        onChange={this._onChange}
        onKeyDown={this._onKeyDown}
      />
```

The braces Im referring to are the ones in the attribute values, i.e., value, onChange and onKeyDown.

Thanks!
Fran

**Comment by mxw** [comment]
I see the following:

![screen shot 2015-01-13 at 1 04 09 am](https://cloud.githubusercontent.com/assets/1013739/5716628/3b48f842-9ac0-11e4-9066-0a9a62dae8ce.png)

Make sure you followed all the installation instructions correctly and have the correct dependencies installed in your bundle.

**Comment by franleplant** [comment]
Maybe the instructions are not clear, this is what I did:

- Installed pangloss's vim-javascript 
- Added the vundle in Vundle and install it

Is there something Im missing?

**Comment by franleplant** [comment]
The problem was that I was using the other syntax highlighting plugin for javascript, when I removed it everything went back to normal.

Is there any plans to make this plugin independent of panglos's one?

**Comment by mxw** [comment]
No.  The default vim Javascript syntax highlighter is too coarse-grained for reasonable extension.

**Comment by franleplant** [comment]
Ok, thanks!
