### ISSUE TITLE
Clobbers my local ftdetect

### ISSUE THREAD

**Issue by lencioni** [mxw/vim-jsx#29]
I'd like to use vim-jsx for the syntax highlighting and indentation features it provides, but it is clobbering [my local ftdetect file](https://github.com/lencioni/dotfiles/blob/293b0df0758aba73dae8379b9a45a72e4891acfe/.vim/ftdetect/jsx.vim) which I rely on for other things in Vim. I think this is happening because everything in this plugin is nested in an `after` directory. Would you be open to a pull request that un-nests everything from the `after` directory?

**Comment by mxw** [comment]
You should move stuff you want to override vim-jsx's ftdetect into your own after/ftdetect.

Pathogen's load order goes something like: local files > bundled files in some order (alphabetical?) > bundled after/ files in some order > local after files.  This gives you control of both the early- and late-loading, which is usually sufficient for most use cases.

**Comment by lencioni** [comment]
Indeed, but I was hoping to avoid this. :)
