### ISSUE TITLE
Support for es6 Classes?

### ISSUE THREAD

**Issue by metasansana** [mxw/vim-jsx#34]
I noticed they were not being indented.

React is investing in the class syntax:
http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by mxw** [comment]
This module is only for JSX syntax and indentation.  Any plain JS or ES6 support is left to the vim-javascript dependency (which, afaict, does support classes now—do you have it properly installed?).

**Comment by metasansana** [comment]
Nevermind, looks like I had some syntax errors.

**Comment by rblakeley** [comment]
@metasansana Do you remember what your syntax errors were that were causing indentation problems? When I `return` for a new line, the previous line is removing all indentation. (In ES6 classes).
