### ISSUE TITLE
No syntax highlighting inside blocks

### ISSUE THREAD

**Issue by wyattanderson** [mxw/vim-jsx#38]
Seeing some very strange behavior now where JSX isn't highlighted inside of any kind of JS block. For example:

![screen shot 2015-04-13 at 2 58 01 pm](https://cloud.githubusercontent.com/assets/492216/7123092/9fb52c32-e1ed-11e4-91c7-dfdcc6578967.png)

Works fine for JSX outside of a block. Don't really know how to test this any further; happy to provide more information. Both `vim-jsx` and `vim-javascript` are up-to-date.

**Comment by mxw** [comment]
Can you link me to your ~/.vimrc, as well as tell me the git hashes of your vim-jsx and pangloss/vim-javascript repos?

I can't reproduce this issue locally.  I also use solarized dark as my colorscheme, and I'm seeing my `=` highlighted green like the `return`, so maybe something is off about your JS syntax package.

**Comment by wyattanderson** [comment]
* `vim-javascript`: `8a409f7`
* `vim-jsx`: `c8fc9ec`
* `.vimrc`: https://gist.github.com/wyattanderson/544e2f5552ccb872ae86

**Comment by mxw** [comment]
Does replacing `syntax on` with `syntax enable` in your ~/.vimrc help?  If not, my best advice is to try bisecting your plugins (or if you don't have many, just remove them all except vim-jsx and vim-javascript, see if that baseline works, and if so, add them back one at a time until you find a conflict).

(You can also try bisecting your ~/.vimrc by inserting `finish` at various points in the file.)

**Comment by wyattanderson** [comment]
Ugh, sorry, my `~/.vim` was a mess and I had a really old JS syntax file lying around that was conflicting with the `vim-javascript` bundle. Really sorry for the wild goose chase :(
