### ISSUE TITLE
Weird syntax highlighting after turning on vim-jsx

### ISSUE THREAD

**Issue by lazywei** [mxw/vim-jsx#42]
Before turning on vim-jsx
![image](https://cloud.githubusercontent.com/assets/2840571/7487990/4dbccd8a-f3f5-11e4-8867-91e12742e7cb.png)

After turning on vim-jsx
![image](https://cloud.githubusercontent.com/assets/2840571/7487986/378acff8-f3f5-11e4-8187-161cb8def64c.png)

**Comment by mxw** [comment]
Unable to repro. Please verify that you (a) have installed all the dependencies required; (b) either have the (deprecated) JSX pragma at the top of your file or have named your file with the .jsx extension; and (c) are not hitting any conflicts with other vim packages (you can test this by just unincluding them and seeing the resultant behavior).
