### ISSUE TITLE
indent error

### ISSUE THREAD

**Issue by hufeng** [mxw/vim-jsx#45]
for example:
```javascript
var About = React.createClass({
  render() {/*cursor is here*/}
});
```

when I typed 'enter', 

```javascript
var About = React.createClass({
 render() {
 }
 });
```

**Comment by mxw** [comment]
I can't repro this.  This is probably a conflict with another package, or you forgot to install the vim-javascript dependency.  Try bisecting your package includes if it's the former, or reading the installation instructions if it's the latter.
