### ISSUE TITLE
No highlighting for children

### ISSUE THREAD

**Issue by davidnormo** [mxw/vim-jsx#47]
Consider this fragment:
```javascript
render() {
   return (
      <div>
         {this.props.children}
      </div>
   );
}
```
The children props section isn't highlighted.
Thanks for writing this bundle, really helpful!

**Comment by mxw** [comment]
Unable to repro. Please verify that you (a) have installed all the dependencies required; (b) either have the (deprecated) JSX pragma at the top of your file or have named your file with the .jsx extension; and (c) are not hitting any conflicts with other vim packages (you can test this by just unincluding them and seeing the resultant behavior).

Additionally, a screenshot of what you see and a description of what you expect (i.e., what specifically you expect to be highlighted) would be useful for future reports.
