### ISSUE TITLE
Indentation not working.

### ISSUE THREAD

**Issue by jakobdamjensen** [mxw/vim-jsx#49]
Using auto indent of entire file all the JSX code gets the same indentation. Does this plugin only provide syntax highlight?

**Comment by mxw** [comment]
It does indentation too, but what you're describing should work.  Can you provide me an example where it breaks for you, as well as a copy of your ~/.vimrc?  Also, make sure you've followed the installation instructions and have the appropriate dependencies.

**Comment by awinecki** [comment]
I'm also having some indentation problems. In my case, inside `.js` files the JSX indentation works fine when I type, but the plugin breaks the regular JS indentation (see screenshot).

**Note**: I'm using this option `let g:jsx_ext_required = 0 " Allow JSX in normal JS files` to have JSX syntax within .js files. (_without using this option, .jsx files don't indent js blocks properly, but .jsx tags seem quite ok. Also, note that I'm using ES6 syntax, maybe it matters here_).

![bad-indent-jsx-vim](https://cloud.githubusercontent.com/assets/656694/8243811/c7d9e5c0-161a-11e5-92d0-85e8dfc65724.gif)

**Comment by mxw** [comment]
Based on your syntax highlighting (in particular, the braces being highlighted), I suspect that you aren't using the same version of pangloss/vim-javascript as I am.  Can you tell me the git hash for the version of that package you're on?

**Comment by lllama** [comment]
I was having the same issue and installing the latest version of [pangloss/vim-javascript] (https://github.com/pangloss/vim-javascript) appears to have fixed it.

**Comment by mxw** [comment]
Closing because this is probably a failure to follow the README instructions, or possibly a conflict with JS syntax packages.
