### ISSUE TITLE
Quotes in tag-text

### ISSUE THREAD

**Issue by Shriken** [mxw/vim-jsx#51]
Strings should be overridden inside of tags (unless they're further enclosed by curlies.

Example: 

    <p>I'm an ugly tag!</p>

**Comment by mxw** [comment]
You need to double-quote these strings; this is a wontfix for now (though feel free to submit a PR).

(I should probably document somewhere that this is a known problem...)

**Comment by Shriken** [comment]
So to be clear the solution is `<p>"I'm an ugly tag!</p>` ?

**Comment by mxw** [comment]
`<p>"I'm an ugly tag!"</p>`

(Need to close the quote.)

I believe that this works—you might have to do `<p>{"I'm an ugly tag!"}</p>`, but IIRC, that has slightly different behavior w.r.t. whitespace.  (I'm not a React/JSX expert, but somebody's gotta write the Vimscript :P)

**Comment by Shriken** [comment]
(Woops, typo.)

Gotcha. Thanks!

**Comment by artemave** [comment]
This for me was a killer. Found the replacement that can cope https://github.com/jsx/jsx.vim
