### ISSUE TITLE
Everything is jsxRegion after a tag

### ISSUE THREAD

**Issue by moll** [mxw/vim-jsx#52]
Hey,

Is it me and my setup or does the simplest example not work?
```js
var React = require("react")

React.createClass({
  render: function() {
    return <div>{this.renderMore()}</div>
  },

  renderMore: function() {
    return <strong>Hello</strong>
  }
})
```
I see `renderMore` and its `function` keyword colored incorrectly. Further inspection tells that `function` is still in the `jsxRegion` context, which I presume should've ended at the `</div>` above.

**Comment by mxw** [comment]
Most likely you did not follow the installation instructions, which requires that you install a Javascript syntax dependency.  If this is not the case, feel free to send me a Gist of your ~/.vimrc and I can attempt to help you debug further.

**Comment by moll** [comment]
I have found that the problem is related to `xml_syntax_folding`. Apparently enabling it via `let xml_syntax_folding=1` breaks JSX.vim.

**Comment by mxw** [comment]
Ah, very interesting—this confirms my belief that JSX probably doesn't work with folding...

I don't have any plans to support syntax folding myself (I find that very few people use the feature).  If you produce a solution, feel free to submit a PR; in the meantime, I'll add a comment to the README about folding causing breakages.  Thanks for sharing!

**Comment by moll** [comment]
Okay. You might want to open this issue to remind yourself to add a README note. ;) These things are easy to forget.

**Comment by mxw** [comment]
It is done.  Thanks for the reminder!
