### ISSUE TITLE
No highlighting in .es6 files

### ISSUE THREAD

**Issue by quozd** [mxw/vim-jsx#55]
Hello,

I'm using react with babeljs transpiler and .es6 extensions. In such files JSX is not highlighted. In .jsx files everything is ok. Any ideas? Thanks.

osx
vim 4.7.712
all plugins are up to date.
[vimrc](https://github.com/quozd/dotfiles/blob/master/.vimrc)

**Comment by t1bb4r** [comment]
I noticed the following two lines in `after/ftdetect/javascript.vim`:
```
autocmd BufNewFile,BufRead *.jsx let b:jsx_ext_found = 1
autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx
```
Try copying that into your .vimrc and replacing `*.jsx` with `*.es6`. Something similar worked for me.

**Comment by mxw** [comment]
Yep, that should work.

**Comment by neutronz** [comment]
@t1bb4r your last comment helped me with es6 files and highlighting as well thanks
