### ISSUE TITLE
Curly brace matching is broken

### ISSUE THREAD

**Issue by Shriken** [mxw/vim-jsx#56]
It seems that open curlies inside of JSX are ignored for brace matching, but close curlies are not. This unbalances the curly count outside the JSX, significantly reducing the value of `%`.

**Comment by mxw** [comment]
I am unable to repro.  Please verify that you are using the required dependency package, pangloss/vim-javascript, and that it isn't a package conflict in your vim config.

Otherwise, please post an example of the problem.

**Comment by Shriken** [comment]
Installing vim-javascript fixes it, thanks. Guess I need to learn to read ._.
