### ISSUE TITLE
Syntax broken for onClick

### ISSUE THREAD

**Issue by fedemp** [mxw/vim-jsx#57]
For the following code, the closing brace is highlighted in a different way. It also breaks indentation when inside a conditional, as the closing brace is seen as closing the conditional.

````jsx
<div onClick={this.props.onClick}>
````

![2015-08-07-114618_403x54_scrot](https://cloud.githubusercontent.com/assets/735314/9138450/422213ec-3cfa-11e5-8790-4f172022f1da.png)

**Comment by mxw** [comment]
I am unable to repro.  Please ensure that your file has JSX syntax enabled (the default requires you to use the .jsx extension) and that you have installed the pangloss/vim-javascript dependency, without conflicts with other JS packages.
