### ISSUE TITLE
Feature request: indenting inside inline XML

### ISSUE THREAD

**Issue by mickhrmweb** [mxw/vim-jsx#58]
Currently, if you use `ggVG=`, it will correctly indent the Javascript but the XML has no nesting.  There is also no indenting when opening and closing tags while typing XML.

The HTML plugin that comes with Vim by default might be a good place to take inspiration, though I'm feeling it wouldn't be trivial to implement.

**Comment by mxw** [comment]
I don't understand the issue you're describing (e.g., what is `ggVG`?).  XMLish tags indent as they would in an XML file—that's half the point of this package (the other half being syntax).

Please verify that you have the appropriate dependencies installed, as specified in the README, and if you do, please provide a gif or video of the issue you're seeing.  You can reopen the issue at that time.
