### ISSUE TITLE
Keywords highlighted as errors with othree/yajs.vim

### ISSUE THREAD

**Issue by simonratner** [mxw/vim-jsx#60]
![yajs-jsx](https://cloud.githubusercontent.com/assets/667283/10441410/1a3531b6-70fd-11e5-90cf-3c251c46ab06.PNG)

I know that only `pangloss/vim-javascript` is officially supported, but this could be a simple fix, depending on what you stance on cross-compatibility is:
```viml
syn cluster javascriptNoReserved add=jsxRegion
```

I've filed a similar issue on the other side: https://github.com/othree/yajs.vim/issues/76

**Comment by mxw** [comment]
I'm happy to support other packages as long as it's nonintrusive—this sounds like it fits the bill.  Put up a PR and I'll merge it.
