### ISSUE TITLE
Conflicts slightly with flow template annotations

### ISSUE THREAD

**Issue by eapache** [mxw/vim-jsx#62]
If you also use flow annotations (http://flowtype.org/) in your javascript, they can confuse the syntax highlighting because flow template types also use tags, e.g. `Array<int>`.

The solution for me was simply to add a `\W` to the front jsx start regex, since real jsx should never immediately follow a word character, and real flow templates should always follow a word character.

If this makes sense to you, it's probably worth adding to master.

**Comment by toroman** [comment]
+1, same issue, same solution

**Comment by mxw** [comment]
This is probably not the solution you want, because it might make the terminal character of whatever syntax element preceded the start tag a part of the start tag.

I've just pushed an update that should solve the problem without this nit—let me know if it doesn't work for you.

**Comment by eapache** [comment]
Thanks!
