### ISSUE TITLE
Possible Highlighting Issue ?

### ISSUE THREAD

**Issue by mzgnr** [mxw/vim-jsx#69]
Thanks for this useful plugin. Is it normal that opening and closing tags are colorised with different colours ?

![screen shot 2015-11-29 at 12 51 29](https://cloud.githubusercontent.com/assets/6003317/11456666/b9026f5a-9698-11e5-9893-dbca5adae90d.png)

**Comment by mxw** [comment]
Have you followed the installation instructions?

**Comment by mzgnr** [comment]
If you mean installing vim-javascript and setting ext_required to false , yes . But it looks more pretty without the vim-javascript for me. The only issue is the closing tags :cry:

**Comment by mzgnr** [comment]
and I have the same issue with vim-javascript

**Comment by mxw** [comment]
I think you're saying that your highlighting issue is coming from not using vim-javascript.

vim-jsx is not supported without vim-javascript, so you should not expect any sane highlighting or indenting without it.

**Comment by mzgnr** [comment]
I have vim-javascript and I have the issue as well. You can look at the sublime version of jsx highlighting 
![screen shot 2015-11-29 at 16 53 43](https://cloud.githubusercontent.com/assets/6003317/11457765/0c5085f4-96ba-11e5-95d2-9d8a18446ec8.png)

**Comment by mxw** [comment]
Can you bisect your ~/.vimrc and let me know what you find?  In other words, keep vim-jsx, but remove everything else, and then add it back a la binary search...
