### ISSUE TITLE
Using HTML for indentation and syntax highlighting instead of XML

### ISSUE THREAD

**Issue by sassanh** [mxw/vim-jsx#71]
Thanks for this helpful extension. I modified it so that it uses HTML for indentation and syntax highlighting instead of XML. Let me know if I should create a pullrequest for this or if using XML is intentional and you still prefer using XML.

**Comment by timoxley** [comment]
+1

**Comment by mxw** [comment]
The XML is intentional—since, after all, custom tag names are not supported in HTML (as far as I know...).  You really can include arbitrary XML as far as I can tell, as long as you define the appropriate React classes, of course.

**Comment by sassanh** [comment]
@mxw as we discussed https://github.com/pangloss/vim-javascript/pull/625#issuecomment-244839437 while I agree with your reasons for using xml. I see benefits using html too. There are few really useful plugins written for html which will work out of the box for jsx if we use html.
As I said there currently I use a modified version of `vim-jsx` with html instead of xml as its syntax/indent backend and it just works perfectly with all those plugins. I thought maybe we can make it an option in `vim-jsx` so that user can chose which backend he wants. I can create a pull request that adds the option. (keeping xml the default.) would you accept such a pr?

**Comment by mxw** [comment]
@sassanh—Hmm, depends on how intrusive the change is, but I'm certainly open to it.

**Comment by sassanh** [comment]
Great, I think I can manage to make it not intrusive at all. Lets see how it goes this weekend.
