### ISSUE TITLE
breaks syntax highlighting

### ISSUE THREAD

**Issue by iwyg** [mxw/vim-jsx#72]
So I use this plugin along with `pangloss/vim-javascript` and I noticed that it breaks parts of the syntax highlighting when writing jsx: 

![broken syntax](https://dl.dropboxusercontent.com/u/17036738/github/issues/jsx_broken_syntax_01.png)

omitting the jsx part seems to fix it
![ok syntax](https://dl.dropboxusercontent.com/u/17036738/github/issues/jsx_broken_syntax_02.png)

can anyone confirm this?

**Comment by iwyg** [comment]
Hm, strange. I figured that defining `g:xml_syntax_folding` anywhere in vimrc is causing this issue (doesn't matter if you set it to 0 or 1)

**Comment by mxw** [comment]
Note that the README states that folding is not supported for vim-jsx...
