### ISSUE TITLE
es6 / jsx format error

### ISSUE THREAD

**Issue by liaohuqiu** [mxw/vim-jsx#77]
![image](https://cloud.githubusercontent.com/assets/4088573/11750305/89ff3eb0-9fe7-11e5-8a68-46ca78cb35fa.png)

The last two brackets are in the wrong position.

**Comment by ksmithbaylor** [comment]
Did you make sure to re-indent the whole file (I used gg=G)? This code sample seems to indent correctly for me:

![image](https://cloud.githubusercontent.com/assets/1709318/11820748/182887ec-a334-11e5-943e-7f283358e91b.png)

**Comment by nivla** [comment]
+1, I have the same problem. The last two brackets are in the wrong position.
```
class App extends Component {
  render() {
    return (
      <div>
        <form action="/">
          <button>
             Click here
          </button>
        </form>
      </div>
    );
  }
}
```
After I open a bracket in a element, the last two brackets are in the wrong position.
````
class App extends Component {
  render() {
    return (
      <div>
        <form action="/">
          <button onClick={this.handleClick.bind(this)}>
          </button>
        </form>
      </div>
    );
}
}
```

**Comment by mxw** [comment]
Unable to repro.  Most likely cause is a failure to follow the installation instructions and include the pangloss/vim-javascript dependency, or a conflict between that package and another JS package.

**Comment by harish2704** [comment]
@liaohuqiu  Hi, I also had the same problem. Some how I fixed this problem using trial and error method.
If you have line like 
```
let xml_syntax_folding=1
```
in your vimrc, try removing it
