### ISSUE TITLE
Doesn't handle JSX block comments

### ISSUE THREAD

**Issue by tribou** [mxw/vim-jsx#81]
Looks like the syntax highlighting breaks after a JSX block comment:

```jsx
      <div>
        <Nav />
          <Button />
          <Table />
          {/*
            <Modal />
            */}
      </div>
```

In the above example, the last two lines lose the syntax highlighting in Vim.

**Comment by mxw** [comment]
You mean that it doesn't handle block comments inside braces which contain a self-closing end tag?  I tried other permutations, and they all seem fine.

Nonetheless, that's pretty strange, and I'll try to fix.

**Comment by tribou** [comment]
Yes, that's correct. I know the `{/*` is an edge case, but that's the only way I found to do a block comment inside a jsx block. Thanks!

**Comment by mxw** [comment]
Thanks for reporting!  I'm pretty sure the fix works for your problem... but please let me know if it breaks things in exciting new ways.
