### ISSUE TITLE
Indentation doesn't work

### ISSUE THREAD

**Issue by mcchrish** [mxw/vim-jsx#82]
Using minimal vimrc.
Relevant plugins: `othree/yajs.vim`, `mxw/vim-jsx`, `gavocanov/vim-js-indent`. Tried to disable `gavocanov/vim-js-indent` but still doesn't work.
![screen shot 2016-02-01 at 8 45 08 pm](https://cloud.githubusercontent.com/assets/7200153/12717862/ade87492-c925-11e5-8e8b-005fc8b1b0e7.png)

**Comment by mxw** [comment]
Seems like a bug in your comprehension of the README:

> This bundle requires pangloss's vim-javascript syntax highlighting.

I'm unable to repro this using vim-javascript.  Definitely feel free to submit a PR for your fix (preferably one that isn't stop-the-world), but I only keep issues open for problems that come up with the Officially Supported Installation.

**Comment by mcchrish** [comment]
Sorry about that. This is definitely not a bug from this repo. `gavocanov/vim-js-indent` is actually based on pangloss's plugin and it was compatible with your plugin for a while until they change up.
