### ISSUE TITLE
Various issues with jsx + arrow functions

### ISSUE THREAD

**Issue by timoxley** [mxw/vim-jsx#84]
Thanks for this great plugin, though there appears to be a number of issues when using arrows inside jsx attributes. Tried to create a bunch of variations that exhibit different problems. `SearchTags4` is the only one that appears to have made it through unscathed.

![image](https://cloud.githubusercontent.com/assets/43438/13098934/596df1ea-d568-11e5-9c28-dccdd185bd40.png)

Also sometimes seems to chew a lot of cpu, creating lots of editing latency, when chaning the lines that are confused, though I can't seem to reproduce with this particular set.

**Comment by mxw** [comment]
Please read the README.

**Comment by timoxley** [comment]
@mxw :+1: my bad.
