### ISSUE TITLE
Colors don't match on closing tags

### ISSUE THREAD

**Issue by diegodesouza** [mxw/vim-jsx#87]
I'm wondering if this was intentional, but the closing tags color don't match the opening ones. Notice the `<div>` and its closing `</div>`.
I'm using the theme called "Tomorrow-night" and have tested with others as well, same issue.   ![screen shot 2016-03-20 at 6 35 21 pm](https://cloud.githubusercontent.com/assets/7575914/13907697/92d63656-eeca-11e5-91a5-06cbbe07bc0f.png)

**Comment by mxw** [comment]
The colorization should match what you see in a regular XML file, and I think different colors is the default.

**Comment by statianzo** [comment]
@diegodesouza I ran into this today. Added this to my vimrc

```viml
highlight link xmlEndTag xmlTag
```

**Comment by aewing** [comment]
For those seeing this error today:
```vim
highlight! link jsxTag jsxCloseTag
```
