### ISSUE TITLE
Unindenting ES7 Properties

### ISSUE THREAD

**Issue by jambonrose** [mxw/vim-jsx#91]
EDIT: I'm tired, and accidentally submitted the issue before I'd finished writing. Apologies for that.

Hi,
I'm currently using vim-jsx to code React/JSX with ES6 and ES7 features enabled (via Babel). Unfortunately, this is confusing vim-jsx. Notably, when I press return on ES7 properties, the line is fully unindented.

For example:

```javascript
    static propTypes = {
      numberInGroup: PropTypes.number,
    }
```

Adding a newline using the return key at the end of any of the lines in the code above will fully unindent that line of code.

For others who may run into the same indenting issue: I've set a local change to fix this, but still use the (super helpful) syntax highlighting.

```vim
" in .vimrc
autocmd FileType javascript.jsx setlocal indentexpr=GetJavascriptIndent()
```

Thanks for a great plugin!

**Comment by mxw** [comment]
It seems that you are experiencing a failure to read the README.  Feel free to re-open, if applicable, once you're back from doing that.

**Comment by jambonrose** [comment]
Hi,
Thanks for the quick response.

Apologies for misreading the instructions. I've updated the ReadMe in #92 to try and help others who might make the same mistakes as me.

Thanks again for a great plugin!
