### ISSUE TITLE
Indention incorrect for JS following JSX

### ISSUE THREAD

**Issue by cvincent** [mxw/vim-jsx#95]
Here is my minimal .vimrc:

```
" Be improved
set nocompatible

" ### VUNDLE

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle self-manages
Plugin 'gmarik/Vundle.vim'
" Modern JavaScript support
Plugin 'pangloss/vim-javascript'
" JSX support
Plugin 'mxw/vim-jsx'
call vundle#end()

filetype plugin indent on
syntax on
set autoindent
set shiftwidth=2
set shiftround
let g:xml_syntax_folding = 0
finish
```

Here is a screenshot of the indention issue, using a minimal file after using `=` on the whole thing:

![screen shot 2016-06-17 at 6 02 31 pm](https://cloud.githubusercontent.com/assets/8297/16166977/b00367f4-34b5-11e6-8c31-d6ab812482c6.png)

Here's another screenshot with a slightly more involved file:

![screen shot 2016-06-17 at 6 05 34 pm](https://cloud.githubusercontent.com/assets/8297/16167013/1c9963f0-34b6-11e6-93e4-8f065f35342a.png)

Strangely, I don't get this particular issue when I set `let g:xml_syntax_folding = 1` (but, as is known, I do end up with other indention issues within the XML portions).

It's been driving me somewhat crazy. Let me know if there's anything else I can provide to help diagnose the problem. And thank you for the plugin! :)

**Comment by mxw** [comment]
Do you have anything in your ~/.vim/ outside of your bundle?

**Comment by mxw** [comment]
I don't use Vundle, but I'm unable to repro this (and this would be a pretty basic failure, in any case).  This is most likely a conflict with some other Vimscript, or an issue with Vundle or how you're invoking it.

**Comment by cvincent** [comment]
Here is my `runtimepath` under the minimal setup (I added newlines for readability):

```
~/.vim,
~/.vim/bundle/Vundle.vim,
~/.vim/bundle/vim-javascript,
~/.vim/bundle/vim-jsx,
/usr/local/Cellar/macvim/7.4-100/MacVim.app/Contents/Resources/vim/vimfiles,
/usr/local/Cellar/macvim/7.4-100/MacVim.app/Contents/Resources/vim/runtime,
/usr/local/Cellar/macvim/7.4-100/MacVim.app/Contents/Resources/vim/vimfiles/after,
~/.vim/after,
~/.vim/bundle/Vundle.vim,
~/.vim/bundle/Vundle.vim/after,
~/.vim/bundle/vim-javascript/after,
~/.vim/bundle/vim-jsx/after
```

I've removed everything from `~/.vim` except the `bundle` directory. Though `~/.vim/after` appears above, the directory itself doesn't exist.

The only other thing I can think of is that maybe my version of MacVim has an old version of some default vim syntax. Do you think that might be the case?

**Comment by cvincent** [comment]
Here is the preamble for my vim installation's `indent/xml.vim`. Is this the same version you have?

```
" Language:	xml
" Maintainer:	Johannes Zellner <johannes@zellner.org>
" Last Change:	2012 Jul 25
" Notes:	1) does not indent pure non-xml code (e.g. embedded scripts)
"		2) will be confused by unbalanced tags in comments
"		or CDATA sections.
"		2009-05-26 patch by Nikolai Weibull
" TODO: 	implement pre-like tags, see xml_indent_open / xml_indent_close
```
