### ISSUE TITLE
es6 files

### ISSUE THREAD

**Issue by anhari** [mxw/vim-jsx#97]
Is there a way to enable this plugin for filenames with only the `es6` extension?

( i.e. `yadda.es6` )

**Comment by mxw** [comment]
You can write ftdetect autocmd's as usual for extensions—just set the syntax to `javascript.jsx`, and both JS and JSX syntax will be loaded.

**Comment by mxw** [comment]
Er, set the filetype, not the syntax.

**Comment by anhari** [comment]
@mxw thanks!
