### ISSUE TITLE
Closing paren in nested jsx has incorrect indentation

### ISSUE THREAD

**Issue by rbong** [mxw/vim-jsx#98]
I have all dependencies. Here is my cut down .vimrc
```vim
au Filetype javascript setlocal expandtab tabstop=2 shiftwidth=2
call plug#begin('~/.vim/plugged')
    Plug 'pangloss/vim-javascript'
    let g:javascript_enable_domhtmlcss = 1
    Plug 'mxw/vim-jsx'
    let g:jsx_ext_required = 0
call plug#end()
filetype plugin indent on
```

Notice the line that the cursor is on has incorrect indent, but several lines later the correct indentation is present on the closing paren.

![2016-07-02-105127_507x421_scrot](https://cloud.githubusercontent.com/assets/5875706/16540927/8dacde8a-4043-11e6-8e4b-17b0c85de5cb.png)

Here is the text.
```javascript
import React, { Component } from 'react';

class Test extends Component {
  render() {
    return (
      <div>
        {
          Object.keys(test).map((test) => {
            return (
              <div>
              </div>
            );
          })
        }
      </div>
    );
  }
}
```

**Comment by mxw** [comment]
An actual bug report of an actual bug by a person who has read the README!  A true unicorn.

I've repro'd this.  I'm not sure off the top of my head why it's happening (since the outer `return ();` indents fine), but thank you for reporting; I will look into it when I have some time.

**Comment by sheerun** [comment]
Similar issue happens when using `?:` operator:

```
<Navbar.Form pullRight>
  {
    auth.loggedIn()
      ? <Button onClick={this.logout}>Log Out</Button>
      : <Button bsStyle="primary" onClick={auth.login}>Log In</Button>
      }
    </Navbar.Form>
```

**Comment by sheerun** [comment]
Actually even without `?:` it indents last `}` wrongly

**Comment by mxw** [comment]
Finally got around to looking at this.  I believe I've fixed the issue (all the issues reported in this thread) by improving the heuristic for detecting whether we've left a jsxRegion across a line break.  Please let me know if you find that this is still a problem—or, of course, if you find any new and exciting problems.

Thanks for reporting!

**Comment by mxw** [comment]
Also, apologies that the fix (and fixes in general) take so long.  I don't do any sort of regular development with JSX, so I have to page a bunch of stuff in to test and fix.  Thanks for your patience!

**Comment by sheerun** [comment]
Works awesome, thank you!

**Comment by rbong** [comment]
Works for me as well.
